Svelte views
datawrapper/frontend pull request #43
Opened 2021-02-03 23:44 UTC by gka

2021-03-23 15:43 UTC, gka commented
TODOs (before merging):

- [ ] get rid of `HelloWorld` view
- [ ] get rid of `AdminPageLayout` and  `MainLayout` (they're neither production ready nor used by any view)

2021-03-23 15:47 UTC, davidkokkelink approved these changes
really cool! looking forward to building lots of stuff in this new environment

2021-03-23 17:08 UTC, gka commented on src/utils/events.js
> +class FrontendEventEmitter extends EventEmitter {
no, only the `eventList` at the bottom is frontend specific. Will move to `service-utils` and use the same in `api`

2021-03-23 17:08 UTC, gka commented on src/utils/l10n.js
> +function getScope(scope, locale = defaultLanguage) {
also `plugin-loader.js`

2021-03-23 17:39 UTC, gka commented on src/utils/events.js
> +class FrontendEventEmitter extends EventEmitter {
see https://github.com/datawrapper/service-utils/pull/6/files

2021-03-23 17:40 UTC, gka commented on src/utils/l10n.js
> +function getScope(scope, locale = defaultLanguage) {
actually, the plugin loading is slightly different (for the view linking), so I'll keep it in frontend.

2021-03-23 17:40 UTC, gka commented on src/utils/svelte-view/context.js
> +                      language: 'en-US'
good point, I think we're storing it in the session somewhere

2021-03-24 08:29 UTC, gka commented on src/utils/svelte-view/context.js
> +                      language: 'en-US'
actually, guests currently can't change their language because of a bug

2021-03-24 08:32 UTC, gka commented on src/utils/svelte-view/context.js
> +                      language: 'en-US'
and we're also returning `en-US` hard-coded in the API https://github.com/datawrapper/api/blob/179392feaee57bddeffaae182ac0d2cf2b34d6a7/src/routes/me/index.js#L119

2021-03-24 08:48 UTC, gka commented on src/utils/svelte-view/context.js
> +                      language: 'en-US'
fixed in https://github.com/datawrapper/api/pull/294

2021-03-24 10:06 UTC, gka commented on src/utils/svelte-view/cache.js
> +// @todo: would be nice to add a watch-mode for development
true

2021-03-24 10:27 UTC, jakubdatawrapper requested changes
Looks great! Among other things, the Svelte2Wrapper is nice.

I have a few code style notes.

I've read about half the PR so far. I will do the rest in an hour.

2021-03-24 10:27 UTC, jakubdatawrapper commented on src/plugin-loader.js
> +                        }
This locale loading is very similar to the one in `server.js`. I would suggest it to extract it into a commonfunction.

2021-03-24 10:27 UTC, jakubdatawrapper commented on src/plugin-loader.js
> +        // await server.app.events.emit(server.app.event.PLUGINS_LOADED, { plugins });
Should this be done or can we remove the comment?

2021-03-24 10:27 UTC, jakubdatawrapper commented on src/plugin-loader.js
> +                const { options = {}, ...plugin } = require(pluginPath);
I would suggest to wrap each of these lines in a separate try..catch, in either of which `logError()` would be called. This would allow us to make the log error message more specific, i.e. "skipped, because frontend.js doesn't exist" or "skipped, because loading frontend.js failed (probably missing dep)".

2021-03-24 10:27 UTC, jakubdatawrapper commented on src/routes/lib.js
> +                    // if (!file.endsWith('.svelte.js') && !file.endsWith('.svelte.ie.js')) return Boom.notFound();
Can we remove the commented out code?

2021-03-24 10:27 UTC, jakubdatawrapper commented on src/plugin-loader.js
> +                        }
There is a third instance of locale loading in `routes/preview/utils.js`.

2021-03-24 10:30 UTC, gka commented on src/plugin-loader.js
> +                const { options = {}, ...plugin } = require(pluginPath);
agree about the second line, but `path.join` is really unlikely to fail, isn't it?

2021-03-24 10:57 UTC, gka commented on src/plugin-loader.js
> +                        }
but all three places are doing different things:
- in `server.js` we're loading the **core locales** which are located within the `frontend` repo (in `locales/*.json`)
- in `plugin-loader.js` we're loading **plugin locales** which are located in plugins (outside of the frontend repo)
- in `routes/preview/utils.js` we're loading locales for `dayjs` and `momentjs` which we keep in a separate npm package `@datawrapper/locales`.

The only thing the three code snippets really have in common is that they're iterating over JSON files in a folder and then parsing the JSON content. However, they then do entirely different things with the parse locale.

So the only way I see we could re-use some code would be a generic `readJSONFilesFromFolder()` method that accepts a callback method.

But actuallly not even that is possible as the `dayjs` and `momentjs` locales aren't even JSON parsed, but passed on as string to the chart renderer.

2021-03-24 12:07 UTC, jakubdatawrapper commented on src/utils/svelte-view/index.js
> +        });
Could we do this directly in `context.js`?

2021-03-24 12:07 UTC, jakubdatawrapper commented on src/utils/svelte-view/index.js
> +        const { ssr, error } = await getView(page);
What is the logic behind the view compilation being split between `index.js`, `cache.js` and `rollup-runtime.js`? I find the code a bit hard to navigate.

2021-03-24 12:09 UTC, jakubdatawrapper commented on src/plugin-loader.js
> +                const { options = {}, ...plugin } = require(pluginPath);
Yes, I guess there would have to be an `isFile()` call.

2021-03-24 12:10 UTC, jakubdatawrapper commented on src/plugin-loader.js
> +                        }
I see. I saw the loop and regex test and that seemed similar. We can keep it as is.

2021-03-24 12:18 UTC, gka commented on src/plugin-loader.js
> +                const { options = {}, ...plugin } = require(pluginPath);
looking at the code again I saw there's already a `try {} catch` around the `require(pluginPath)`. Since that require call is really the only thing that can go wrong (`path.join` is just a string concatenation) I don't think we need an extra `try catch` here.

2021-03-24 12:21 UTC, jakubdatawrapper commented on src/plugin-loader.js
> +                const { options = {}, ...plugin } = require(pluginPath);
The idea was that we can improve the error message because we can tell whether `frontend.js` exists or not.

2021-03-24 12:21 UTC, jakubdatawrapper commented on src/plugin-loader.js
> +                }
There is also this.

2021-03-24 12:21 UTC, gka commented on src/utils/svelte-view/cache.js
> +        });
good catch, I added a line that [unsets the error on successful compilation](https://github.com/datawrapper/frontend/blob/0786c8c0e8c11bd705cc95e5a210984f9ffaab66/src/utils/svelte-view/cache.js#L85)

2021-03-24 12:23 UTC, jakubdatawrapper commented on src/utils/svelte-view/cache.js
> +        });
Would the compile ever be triggered though? There is the `if (!cache.has(page)) {` condition.

2021-03-24 12:23 UTC, gka commented on src/utils/svelte-view/index.js
> +        });
Unfortunately not, because we still need the stores for server-side rendering. We only want to empty them for client-side rendering.

2021-03-24 12:24 UTC, jakubdatawrapper commented on src/utils/svelte-view/index.js
> +        });
I see! Thanks for the explanation.

2021-03-24 12:27 UTC, gka commented on src/utils/svelte-view/cache.js
> +        });
well, the only way a broken Svelte template could be fixed while the server is running is in DEV mode, in which case compile is triggered by the `watch` command, regardless of the cache, see [here](https://github.com/datawrapper/frontend/blob/9e076ebb17c1ce4e24b51a211fa4efae292d41a2/src/utils/svelte-view/cache.js#L46-L52)

2021-03-24 12:37 UTC, jakubdatawrapper commented on src/utils/svelte-view/cache.js
> +        });
Ok

2021-03-24 12:41 UTC, gka commented on src/utils/svelte-view/index.js
> +        const { ssr, error } = await getView(page);
**rollup-runtime.js** contains the "raw" rollup build setup and exports the `watch` and  `build` methods. I think it nicely contains what we used to put into `rollup.config.js`, so I'd vote to keep it.

**index.js** exports a single `compile` method that follows the [`hapi/vision`](https://hapi.dev/module/vision/#introduction) convention so we can use the [`h.view()`](https://github.com/datawrapper/frontend/blob/9e076ebb17c1ce4e24b51a211fa4efae292d41a2/src/routes/hello.js#L15-L19) API from vision.

**cache.js** handles the caching logic that prevents the views to be compiled on every request.

2021-03-24 12:42 UTC, gka commented on src/plugin-loader.js
> +                }
but that's not an error, as plugins don't have to define a `frontend.js`. It simply means that they don't want to hook into the frontend service (they can still have an `api.js` or `crons.js`).

2021-03-24 12:44 UTC, gka commented on src/plugin-loader.js
> +                const { options = {}, ...plugin } = require(pluginPath);
true, we could filter the plugin list first to get rid of those that don't have a `frontend.js` right away

2021-03-24 12:47 UTC, gka commented on src/plugin-loader.js
> +                const { options = {}, ...plugin } = require(pluginPath);
what do you think about this https://github.com/datawrapper/frontend/pull/43/commits/f88f79488216f819c55e321ff83bc8997906057b?

2021-03-24 12:48 UTC, gka commented on src/plugin-loader.js
> +                const { options = {}, ...plugin } = require(pluginPath);
(sorry I also had to rename `root` to `pluginRoot` as the syntax highlighting confused me)

2021-03-24 12:48 UTC, jakubdatawrapper commented on src/plugin-loader.js
> +                const { options = {}, ...plugin } = require(pluginPath);
Awesome!

2021-03-24 12:50 UTC, gka commented on src/plugin-loader.js
> +                }
changed this code so that plugins get filtered before they're being loaded

2021-03-24 12:53 UTC, gka commented on src/utils/svelte-view/index.js
> +        const { ssr, error } = await getView(page);
the only way I could move the stuff from `cache.js` into `index.js` is to export the `prepareView` method etc as properties of the compile method, which would be rather ugly.

2021-03-24 13:46 UTC, jakubdatawrapper commented on src/utils/svelte-view/cache.js
> +            cache.set(page, view);
This is somewhat strange. The cache can contain either a transpiled page (if `transpileView` runs) or not a transpiled page and there is no way to know what is stored in the cache.

2021-04-07 08:37 UTC, gka commented on src/utils/svelte-view/cache.js
> +            cache.set(page, view);
I agree that it's strange to store multiple values behind the same cache key. Would you rather split it up into keys like `csr/HelloWorld.svelte`, `ssr/HelloWorld.svelte`, `error/HelloWorld.svelte` and `csrTranspiled/HelloWorld.svelte`?

2021-04-07 11:31 UTC, jakubdatawrapper commented on src/utils/svelte-view/cache.js
> +            cache.set(page, view);
Looking at the current code, I don't think we have the problem anymore, because we don't cache the transpiled page anymore.

2021-04-07 12:15 UTC, jakubdatawrapper commented on src/utils/svelte-view/cache.js
> +            cache.set(page, view);
CSR and SSR are always built at the same time, so we don't need to distinguish the cache there. But the error case could still be a problem, since `compilePage()` can return a view only with the `error` property. So yes, I would split the cache keys as you suggest to something like `csr+ssr/HelloWorld.svelte` and `error/HelloWorld.svelte`.

2021-04-07 12:32 UTC, jakubdatawrapper approved these changes
Looks great. Thanks so much for all this work!

Apart from splitting the cache keys and removing the hellow world views, as you mention above, I don't see anything keeping us from merging this :rocket:

2021-04-12 06:47 UTC, gka commented
I decided to keep the hello world view for now so we have at least one route for testing, But it will only show up in dev mode, so it  won't be visible in production.

2021-04-12 07:36 UTC, gka commented
@jakubdatawrapper  i looked into splitting the cache keys again and to be honest, I don't see a lot of benefits that would justify the quite significant refactoring. Aside from the transpiled code, the value that's stored per cache key is the result of the `build()` step which is always executed simultaneously and the results are always needed in combination. Sure, we could store the code bundles and the source maps separately and then query them separately when we need them. But in my opinion that only makes sense if the cache  keys can be _generated_ separately, too. But I can't generate the csr source map without generating  the csr bundle and to make sure csr and ssr are in sync we should also always generate both of them.

So I'd vote to leave it as it is for now.

2021-04-12 12:11 UTC, jakubdatawrapper commented
Ok, let's keep the cache as it is, no problem. The important issue I had with the code was "resolved" by commit https://github.com/datawrapper/frontend/pull/43/commits/4f913e319643dd0263904aff781dbbb937d18aea, when we stopped caching the transpiled view.

2021-04-12 12:14 UTC, gka commented
actually we're still caching the transpiled view. [here](https://github.com/datawrapper/frontend/blob/cc5b8a177f1991d2d945afaf78399e497ce8da8c/src/utils/svelte-view/index.js#L84-L95) we're checking if `view.csrBabel` exists and if it doesn't we're setting it as property of the `view` object, a reference to which is being cached.

2021-04-12 14:07 UTC, merged