Include team custom locale configurations with locale data
datawrapper/frontend pull request #53
Opened 2021-03-31 13:02 UTC by elanals

To then get applied in chart-core, so that teams can configure adjustments to their chosen locales.

2021-04-05 23:18 UTC, davidkokkelink requested changes

2021-04-05 23:18 UTC, davidkokkelink commented on src/routes/preview/index.js
> +                const team = chart.organizationId ? await api(`/teams/${chart.organizationId}`) : {};
`/teams/:id` only returns the `settings` object for team admins (see [here](https://github.com/datawrapper/api/blob/master/src/routes/teams/%7Bid%7D/index.js#L140-L152)), so we need to find a different solution for this.

i think making a direct orm call similar to how it's done in the API pr would be fine.

2021-04-07 09:07 UTC, elanals commented
Changed to direct ORM call and also changed `loadVendorLocale` to return `'null'` if no corresponding locale is found.

2021-04-07 09:16 UTC, davidkokkelink approved these changes

2021-04-07 15:20 UTC, merged